name = "PE-Fortran"
version = "0.4.0"
license = "MIT"
maintainer = "htang2@alaska.edu"
author = "Han Tang"
copyright = "Copyright 2019-2023 Han Tang"
description = "Solutions to Project Euler problems written by modern Fortran"
keywords = ["fortran", "modern-fortran", "project-euler-solutions"]
homepage = "https://github.com/han190/PE-Fortran"

[library]
source-dir = "src"
include-dir = "src"

[[executable]]
name = "ProjectEuler"
source-dir = "src"
main = "project_euler.f90"