name = "PE-Fortran"
version = "0.0.1"
license = "MIT"
maintainer = "htang2@alaska.edu"
author = "Han Tang"
copyright = "Copyright 2019-2021 Han Tang"
description = "Solutions to Project Euler problems written by modern Fortran"
keywords = ["fortran", "modern-fortran", "project-euler-solutions"]
homepage = "https://github.com/han190/PE-Fortran"

[ library ]
source-dir = "src"

[[ test ]]
name = "PE-Fortran-Test-euler_multiprecision_m"
source-dir = "src/test/test_euler_multiprecision_m"
main = "test_euler_multiprecision_m.f90"

[[ test ]]
name = "PE-Fortran-Test-euler_primes_m"
source-dir = "src/test/test_euler_primes_m"
main = "test_euler_primes_m.f90"

[[ executable ]]
name = "PE-Fortran"
source-dir = "src/app"
main = "euler_main.f90"