name = "PE-Fortran"
version = "0.0.3"
license = "MIT"
maintainer = "htang2@alaska.edu"
author = "Han Tang"
copyright = "Copyright 2019-2021 Han Tang"
description = "Solutions to Project Euler problems written by modern Fortran"
keywords = ["fortran", "modern-fortran", "project-euler-solutions"]
homepage = "https://github.com/han190/PE-Fortran"

[dependencies]
stdlib = {git="https://github.com/fortran-lang/stdlib", branch="stdlib-fpm"}

[ library ]
source-dir = "src-fpm"

[[ test ]]
name = "multiprecision_test"
source-dir = "src-fpm/test"
main = "multiprecision_test.f90"

[[ test ]]
name = "utility_test"
source-dir = "src-fpm/test"
main = "utility_test.f90"

[[ executable ]]
name = "PE-Fortran"
source-dir = "src-fpm/app"
main = "project_euler.f90"