name = "PE_Fortran_Solution"
version = "0.0.1"
license = "MIT"
maintainer = "htang2@alaska.edu"
author = "Han Tang"
copyright = "Copyright 2019 - 2021 Han Tang"
homepage = "https://github.com/han190/PE-Fortran"

[ library ]
source-dir = "src"

[[ executable ]]
name = "PE-Fortran"
source-dir = "app"
main = "euler_main.f90"