name = "PE-Fortran"
version = "0.0.1"
license = "MIT"
maintainer = "htang2@alaska.edu"
author = "Han Tang"
copyright = "Copyright 2019-2021 Han Tang"
description = "Solutions to Project Euler problems written by modern Fortran"
keywords = ["fortran", "modern-fortran", "project-euler-solutions"]
homepage = "https://github.com/han190/PE-Fortran"

[ library ]
source-dir = "src"

[[ test ]]
name = "test_linked_list_m"
source-dir = "src/test/"
main = "test_linked_list_m.f90"

[[ test ]]
name = "PE-Fortran-Test-euler_multiprecision_m"
source-dir = "src/test/"
main = "test_multiprecision_m.f90"

[[ test ]]
name = "PE-Fortran-Test-euler_primes_m"
source-dir = "src/test/"
main = "test_prime_m.f90"

[[ test ]]
name = "PE-Fortran-Test-euler_utility_m"
source-dir = "src/test/"
main = "test_utility_m.f90"

[[ executable ]]
name = "PE-Fortran"
source-dir = "src/app"
main = "project_euler.f90"