module euler_interface_m
    ! This file is automatically generated. 
    ! Do not modify it!
    use iso_fortran_env, only: int64
    use euler_utils_m
    implicit none

    interface

        module character(len=20) function euler0001()
        end function euler0001

        module character(len=20) function euler0002()
        end function euler0002

        module character(len=20) function euler0003()
        end function euler0003

        module character(len=20) function euler0004()
        end function euler0004

        module character(len=20) function euler0005()
        end function euler0005

        module character(len=20) function euler0006()
        end function euler0006

        module character(len=20) function euler0007()
        end function euler0007

        module character(len=20) function euler0008()
        end function euler0008

        module character(len=20) function euler0009()
        end function euler0009

        module character(len=20) function euler0010()
        end function euler0010

        module character(len=20) function euler0011()
        end function euler0011

        module character(len=20) function euler0012()
        end function euler0012

        module character(len=20) function euler0013()
        end function euler0013

        module character(len=20) function euler0014()
        end function euler0014

        module character(len=20) function euler0015()
        end function euler0015

        module character(len=20) function euler0016()
        end function euler0016

        module character(len=20) function euler0017()
        end function euler0017

        module character(len=20) function euler0018()
        end function euler0018

        module character(len=20) function euler0019()
        end function euler0019

        module character(len=20) function euler0020()
        end function euler0020

        module character(len=20) function euler0021()
        end function euler0021

        module character(len=20) function euler0022()
        end function euler0022

        module character(len=20) function euler0023()
        end function euler0023

        module character(len=20) function euler0024()
        end function euler0024

        module character(len=20) function euler0025()
        end function euler0025

        module character(len=20) function euler0026()
        end function euler0026

        module character(len=20) function euler0027()
        end function euler0027

        module character(len=20) function euler0028()
        end function euler0028

        module character(len=20) function euler0029()
        end function euler0029

        module character(len=20) function euler0030()
        end function euler0030

        module character(len=20) function euler0031()
        end function euler0031

        module character(len=20) function euler0032()
        end function euler0032

        module character(len=20) function euler0033()
        end function euler0033

        module character(len=20) function euler0034()
        end function euler0034

        module character(len=20) function euler0035()
        end function euler0035

        module character(len=20) function euler0036()
        end function euler0036

        module character(len=20) function euler0037()
        end function euler0037

        module character(len=20) function euler0038()
        end function euler0038

        module character(len=20) function euler0039()
        end function euler0039

        module character(len=20) function euler0040()
        end function euler0040

        module character(len=20) function euler0041()
        end function euler0041

        module character(len=20) function euler0042()
        end function euler0042

        module character(len=20) function euler0043()
        end function euler0043

        module character(len=20) function euler0044()
        end function euler0044

        module character(len=20) function euler0045()
        end function euler0045

        module character(len=20) function euler0046()
        end function euler0046

        module character(len=20) function euler0047()
        end function euler0047

        module character(len=20) function euler0048()
        end function euler0048

        module character(len=20) function euler0049()
        end function euler0049

        module character(len=20) function euler0050()
        end function euler0050

        module character(len=20) function euler0051()
        end function euler0051

        module character(len=20) function euler0052()
        end function euler0052

        module character(len=20) function euler0053()
        end function euler0053

        module character(len=20) function euler0054()
        end function euler0054

        module character(len=20) function euler0055()
        end function euler0055

        module character(len=20) function euler0056()
        end function euler0056

        module character(len=20) function euler0057()
        end function euler0057

        module character(len=20) function euler0058()
        end function euler0058

    end interface

end module euler_interface_m
