module euler_prob_api_m
    ! This file is automatically generated. 
    ! Do not modify it!
    use euler_interface_m
    implicit none

    type :: euler_probs_t
        procedure(euler_prob_x), nopass, pointer :: ans
        type(euler_probs_t), pointer :: next => null()
    end type euler_probs_t

    abstract interface
        character(len=20) function euler_prob_x()
        end function euler_prob_x
    end interface

contains

    subroutine euler_init(probs)
        type(euler_probs_t), intent(out) :: probs(:)

        probs(   1)%ans => euler0001
        probs(   2)%ans => euler0002
        probs(   3)%ans => euler0003
        probs(   4)%ans => euler0004
        probs(   5)%ans => euler0005
        probs(   6)%ans => euler0006
        probs(   7)%ans => euler0007
        probs(   8)%ans => euler0008
        probs(   9)%ans => euler0009
        probs(  10)%ans => euler0010
        probs(  11)%ans => euler0011
        probs(  12)%ans => euler0012
        probs(  13)%ans => euler0013
        probs(  14)%ans => euler0014
        probs(  15)%ans => euler0015
        probs(  16)%ans => euler0016
        probs(  17)%ans => euler0017
        probs(  18)%ans => euler0018
        probs(  19)%ans => euler0019
        probs(  20)%ans => euler0020
        probs(  21)%ans => euler0021
        probs(  22)%ans => euler0022
        probs(  23)%ans => euler0023
        probs(  24)%ans => euler0024
        probs(  25)%ans => euler0025
        probs(  26)%ans => euler0026
        probs(  27)%ans => euler0027
        probs(  28)%ans => euler0028
        probs(  29)%ans => euler0029
        probs(  30)%ans => euler0030
        probs(  31)%ans => euler0031
        probs(  32)%ans => euler0032
        probs(  33)%ans => euler0033
        probs(  34)%ans => euler0034
        probs(  35)%ans => euler0035
        probs(  36)%ans => euler0036
        probs(  37)%ans => euler0037
        probs(  38)%ans => euler0038
        probs(  39)%ans => euler0039
        probs(  40)%ans => euler0040
        probs(  41)%ans => euler0041
        probs(  42)%ans => euler0042
        probs(  43)%ans => euler0043
        probs(  44)%ans => euler0044
        probs(  45)%ans => euler0045
        probs(  46)%ans => euler0046
        probs(  47)%ans => euler0047
        probs(  48)%ans => euler0048
        probs(  49)%ans => euler0049
        probs(  50)%ans => euler0050
        probs(  51)%ans => euler0051
        probs(  52)%ans => euler0052
        probs(  53)%ans => euler0053
        probs(  54)%ans => euler0054
        probs(  55)%ans => euler0055
        probs(  56)%ans => euler0056
        probs(  57)%ans => euler0057
        probs(  58)%ans => euler0058
    end subroutine euler_init

end module euler_prob_api_m
