name: PE-Fortran
run-name: Testing PE-Fortran by ${{ github.actor }}
on: [push]

jobs:
  Run-With-FPM:
    runs-on: ubuntu-latest
    steps:
      - uses: fortran-lang/setup-fpm@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test with FPM
        run: fpm run
        working-directory: ./
